//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.08 at 03:36:51 PM CEST 
//


package com.project.ws;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fakturaStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fakturaStatus"
})
@XmlRootElement(name = "importFakturaResponse")
public class ImportFakturaResponse {

    @XmlElement(required = true)
    protected String fakturaStatus;

    /**
     * Gets the value of the fakturaStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFakturaStatus() {
        return fakturaStatus;
    }

    /**
     * Sets the value of the fakturaStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFakturaStatus(String value) {
        this.fakturaStatus = value;
    }

}
