//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.08 at 05:19:37 PM CEST 
//


package com.project.ws;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="izvod" type="{http://poslovna.com/soap-example}dnevniIzvodXML"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "izvod"
})
@XmlRootElement(name = "importIzvodRequest")
public class ImportIzvodRequest {

    @XmlElement(required = true)
    protected DnevniIzvodXML izvod;

    /**
     * Gets the value of the izvod property.
     * 
     * @return
     *     possible object is
     *     {@link DnevniIzvodXML }
     *     
     */
    public DnevniIzvodXML getIzvod() {
        return izvod;
    }

    /**
     * Sets the value of the izvod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DnevniIzvodXML }
     *     
     */
    public void setIzvod(DnevniIzvodXML value) {
        this.izvod = value;
    }

}
