//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.08 at 05:19:37 PM CEST 
//


package com.project.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.poslovna.soap_example package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NalogZaPlacanje_QNAME = new QName("http://poslovna.com/soap-example", "nalogZaPlacanje");
    private final static QName _Faktura_QNAME = new QName("http://poslovna.com/soap-example", "faktura");
    private final static QName _Preduzece_QNAME = new QName("http://poslovna.com/soap-example", "preduzece");
    private final static QName _Adresa_QNAME = new QName("http://poslovna.com/soap-example", "adresa");
    private final static QName _StavkaDnevnogIzvoda_QNAME = new QName("http://poslovna.com/soap-example", "stavkaDnevnogIzvoda");
    private final static QName _StavkaFakture_QNAME = new QName("http://poslovna.com/soap-example", "stavkaFakture");
    private final static QName _DnevniIzvod_QNAME = new QName("http://poslovna.com/soap-example", "dnevniIzvod");
    private final static QName _Narudzbenica_QNAME = new QName("http://poslovna.com/soap-example", "narudzbenica");
    private final static QName _StavkaNarudzbenice_QNAME = new QName("http://poslovna.com/soap-example", "stavkaNarudzbenice");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.poslovna.soap_example
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DnevniIzvodXML }
     * 
     */
    public DnevniIzvodXML createDnevniIzvodXML() {
        return new DnevniIzvodXML();
    }

    /**
     * Create an instance of {@link FakturaXML }
     * 
     */
    public FakturaXML createFakturaXML() {
        return new FakturaXML();
    }

    /**
     * Create an instance of {@link ImportFakturaRequest }
     * 
     */
    public ImportFakturaRequest createImportFakturaRequest() {
        return new ImportFakturaRequest();
    }

    /**
     * Create an instance of {@link StavkaFaktureXML }
     * 
     */
    public StavkaFaktureXML createStavkaFaktureXML() {
        return new StavkaFaktureXML();
    }

    /**
     * Create an instance of {@link StavkaDnevnogIzvodaXML }
     * 
     */
    public StavkaDnevnogIzvodaXML createStavkaDnevnogIzvodaXML() {
        return new StavkaDnevnogIzvodaXML();
    }

    /**
     * Create an instance of {@link StavkaNarudzbeniceXML }
     * 
     */
    public StavkaNarudzbeniceXML createStavkaNarudzbeniceXML() {
        return new StavkaNarudzbeniceXML();
    }

    /**
     * Create an instance of {@link NarudzbenicaXML }
     * 
     */
    public NarudzbenicaXML createNarudzbenicaXML() {
        return new NarudzbenicaXML();
    }

    /**
     * Create an instance of {@link ImportFakturaResponse }
     * 
     */
    public ImportFakturaResponse createImportFakturaResponse() {
        return new ImportFakturaResponse();
    }

    /**
     * Create an instance of {@link ImportIzvodResponse }
     * 
     */
    public ImportIzvodResponse createImportIzvodResponse() {
        return new ImportIzvodResponse();
    }

    /**
     * Create an instance of {@link ImportIzvodRequest }
     * 
     */
    public ImportIzvodRequest createImportIzvodRequest() {
        return new ImportIzvodRequest();
    }

    /**
     * Create an instance of {@link NalogZaPlacanjeXML }
     * 
     */
    public NalogZaPlacanjeXML createNalogZaPlacanjeXML() {
        return new NalogZaPlacanjeXML();
    }

    /**
     * Create an instance of {@link ExportNalogaResponse }
     * 
     */
    public ExportNalogaResponse createExportNalogaResponse() {
        return new ExportNalogaResponse();
    }

    /**
     * Create an instance of {@link AdresaXML }
     * 
     */
    public AdresaXML createAdresaXML() {
        return new AdresaXML();
    }

    /**
     * Create an instance of {@link ExportNalogaRequest }
     * 
     */
    public ExportNalogaRequest createExportNalogaRequest() {
        return new ExportNalogaRequest();
    }

    /**
     * Create an instance of {@link PreduzeceXML }
     * 
     */
    public PreduzeceXML createPreduzeceXML() {
        return new PreduzeceXML();
    }

    /**
     * Create an instance of {@link DnevniIzvodXML.StavkaDnevnogIzvodaList }
     * 
     */
    public DnevniIzvodXML.StavkaDnevnogIzvodaList createDnevniIzvodXMLStavkaDnevnogIzvodaList() {
        return new DnevniIzvodXML.StavkaDnevnogIzvodaList();
    }

    /**
     * Create an instance of {@link FakturaXML.StavkaFaktureList }
     * 
     */
    public FakturaXML.StavkaFaktureList createFakturaXMLStavkaFaktureList() {
        return new FakturaXML.StavkaFaktureList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NalogZaPlacanjeXML }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://poslovna.com/soap-example", name = "nalogZaPlacanje")
    public JAXBElement<NalogZaPlacanjeXML> createNalogZaPlacanje(NalogZaPlacanjeXML value) {
        return new JAXBElement<NalogZaPlacanjeXML>(_NalogZaPlacanje_QNAME, NalogZaPlacanjeXML.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FakturaXML }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://poslovna.com/soap-example", name = "faktura")
    public JAXBElement<FakturaXML> createFaktura(FakturaXML value) {
        return new JAXBElement<FakturaXML>(_Faktura_QNAME, FakturaXML.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PreduzeceXML }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://poslovna.com/soap-example", name = "preduzece")
    public JAXBElement<PreduzeceXML> createPreduzece(PreduzeceXML value) {
        return new JAXBElement<PreduzeceXML>(_Preduzece_QNAME, PreduzeceXML.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdresaXML }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://poslovna.com/soap-example", name = "adresa")
    public JAXBElement<AdresaXML> createAdresa(AdresaXML value) {
        return new JAXBElement<AdresaXML>(_Adresa_QNAME, AdresaXML.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StavkaDnevnogIzvodaXML }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://poslovna.com/soap-example", name = "stavkaDnevnogIzvoda")
    public JAXBElement<StavkaDnevnogIzvodaXML> createStavkaDnevnogIzvoda(StavkaDnevnogIzvodaXML value) {
        return new JAXBElement<StavkaDnevnogIzvodaXML>(_StavkaDnevnogIzvoda_QNAME, StavkaDnevnogIzvodaXML.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StavkaFaktureXML }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://poslovna.com/soap-example", name = "stavkaFakture")
    public JAXBElement<StavkaFaktureXML> createStavkaFakture(StavkaFaktureXML value) {
        return new JAXBElement<StavkaFaktureXML>(_StavkaFakture_QNAME, StavkaFaktureXML.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DnevniIzvodXML }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://poslovna.com/soap-example", name = "dnevniIzvod")
    public JAXBElement<DnevniIzvodXML> createDnevniIzvod(DnevniIzvodXML value) {
        return new JAXBElement<DnevniIzvodXML>(_DnevniIzvod_QNAME, DnevniIzvodXML.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NarudzbenicaXML }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://poslovna.com/soap-example", name = "narudzbenica")
    public JAXBElement<NarudzbenicaXML> createNarudzbenica(NarudzbenicaXML value) {
        return new JAXBElement<NarudzbenicaXML>(_Narudzbenica_QNAME, NarudzbenicaXML.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StavkaNarudzbeniceXML }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://poslovna.com/soap-example", name = "stavkaNarudzbenice")
    public JAXBElement<StavkaNarudzbeniceXML> createStavkaNarudzbenice(StavkaNarudzbeniceXML value) {
        return new JAXBElement<StavkaNarudzbeniceXML>(_StavkaNarudzbenice_QNAME, StavkaNarudzbeniceXML.class, null, value);
    }

}
