//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.08 at 10:06:01 AM CEST 
//


package com.project.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.poslovna.soap_example package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Faktura_QNAME = new QName("http://poslovna.com/soap-example", "faktura");
    private final static QName _Preduzece_QNAME = new QName("http://poslovna.com/soap-example", "preduzece");
    private final static QName _Adresa_QNAME = new QName("http://poslovna.com/soap-example", "adresa");
    private final static QName _StavkaFakture_QNAME = new QName("http://poslovna.com/soap-example", "stavkaFakture");
    private final static QName _Narudzbenica_QNAME = new QName("http://poslovna.com/soap-example", "narudzbenica");
    private final static QName _StavkaNarudzbenice_QNAME = new QName("http://poslovna.com/soap-example", "stavkaNarudzbenice");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.poslovna.soap_example
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Faktura }
     * 
     */
    public Faktura createFaktura() {
        return new Faktura();
    }

    /**
     * Create an instance of {@link ImportFakturaRequest }
     * 
     */
    public ImportFakturaRequest createImportFakturaRequest() {
        return new ImportFakturaRequest();
    }

    /**
     * Create an instance of {@link StavkaFakture }
     * 
     */
    public StavkaFakture createStavkaFakture() {
        return new StavkaFakture();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link StavkaNarudzbenice }
     * 
     */
    public StavkaNarudzbenice createStavkaNarudzbenice() {
        return new StavkaNarudzbenice();
    }

    /**
     * Create an instance of {@link Narudzbenica }
     * 
     */
    public Narudzbenica createNarudzbenica() {
        return new Narudzbenica();
    }

    /**
     * Create an instance of {@link Preduzece }
     * 
     */
    public Preduzece createPreduzece() {
        return new Preduzece();
    }

    /**
     * Create an instance of {@link ImportFakturaResponse }
     * 
     */
    public ImportFakturaResponse createImportFakturaResponse() {
        return new ImportFakturaResponse();
    }

    /**
     * Create an instance of {@link Faktura.StavkaFaktureList }
     * 
     */
    public Faktura.StavkaFaktureList createFakturaStavkaFaktureList() {
        return new Faktura.StavkaFaktureList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Faktura }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://poslovna.com/soap-example", name = "faktura")
    public JAXBElement<Faktura> createFaktura(Faktura value) {
        return new JAXBElement<Faktura>(_Faktura_QNAME, Faktura.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Preduzece }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://poslovna.com/soap-example", name = "preduzece")
    public JAXBElement<Preduzece> createPreduzece(Preduzece value) {
        return new JAXBElement<Preduzece>(_Preduzece_QNAME, Preduzece.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Adresa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://poslovna.com/soap-example", name = "adresa")
    public JAXBElement<Adresa> createAdresa(Adresa value) {
        return new JAXBElement<Adresa>(_Adresa_QNAME, Adresa.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StavkaFakture }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://poslovna.com/soap-example", name = "stavkaFakture")
    public JAXBElement<StavkaFakture> createStavkaFakture(StavkaFakture value) {
        return new JAXBElement<StavkaFakture>(_StavkaFakture_QNAME, StavkaFakture.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Narudzbenica }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://poslovna.com/soap-example", name = "narudzbenica")
    public JAXBElement<Narudzbenica> createNarudzbenica(Narudzbenica value) {
        return new JAXBElement<Narudzbenica>(_Narudzbenica_QNAME, Narudzbenica.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StavkaNarudzbenice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://poslovna.com/soap-example", name = "stavkaNarudzbenice")
    public JAXBElement<StavkaNarudzbenice> createStavkaNarudzbenice(StavkaNarudzbenice value) {
        return new JAXBElement<StavkaNarudzbenice>(_StavkaNarudzbenice_QNAME, StavkaNarudzbenice.class, null, value);
    }

}
