//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.08 at 10:06:01 AM CEST 
//


package com.project.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stavkaFakture complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stavkaFakture">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="osnovica" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="iznosRabata" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="procenatRabata" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="stopaPdv" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="iznosPdv" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="jedinicnaCena" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="kolicinaStavkeFakture" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ukupanIznos" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="proizvod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stavkaFakture", propOrder = {
    "id",
    "osnovica",
    "iznosRabata",
    "procenatRabata",
    "stopaPdv",
    "iznosPdv",
    "jedinicnaCena",
    "kolicinaStavkeFakture",
    "ukupanIznos",
    "proizvod"
})
public class StavkaFakture {

    protected long id;
    protected double osnovica;
    protected double iznosRabata;
    protected double procenatRabata;
    protected double stopaPdv;
    protected double iznosPdv;
    protected double jedinicnaCena;
    protected double kolicinaStavkeFakture;
    protected double ukupanIznos;
    @XmlElement(required = true)
    protected String proizvod;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the osnovica property.
     * 
     */
    public double getOsnovica() {
        return osnovica;
    }

    /**
     * Sets the value of the osnovica property.
     * 
     */
    public void setOsnovica(double value) {
        this.osnovica = value;
    }

    /**
     * Gets the value of the iznosRabata property.
     * 
     */
    public double getIznosRabata() {
        return iznosRabata;
    }

    /**
     * Sets the value of the iznosRabata property.
     * 
     */
    public void setIznosRabata(double value) {
        this.iznosRabata = value;
    }

    /**
     * Gets the value of the procenatRabata property.
     * 
     */
    public double getProcenatRabata() {
        return procenatRabata;
    }

    /**
     * Sets the value of the procenatRabata property.
     * 
     */
    public void setProcenatRabata(double value) {
        this.procenatRabata = value;
    }

    /**
     * Gets the value of the stopaPdv property.
     * 
     */
    public double getStopaPdv() {
        return stopaPdv;
    }

    /**
     * Sets the value of the stopaPdv property.
     * 
     */
    public void setStopaPdv(double value) {
        this.stopaPdv = value;
    }

    /**
     * Gets the value of the iznosPdv property.
     * 
     */
    public double getIznosPdv() {
        return iznosPdv;
    }

    /**
     * Sets the value of the iznosPdv property.
     * 
     */
    public void setIznosPdv(double value) {
        this.iznosPdv = value;
    }

    /**
     * Gets the value of the jedinicnaCena property.
     * 
     */
    public double getJedinicnaCena() {
        return jedinicnaCena;
    }

    /**
     * Sets the value of the jedinicnaCena property.
     * 
     */
    public void setJedinicnaCena(double value) {
        this.jedinicnaCena = value;
    }

    /**
     * Gets the value of the kolicinaStavkeFakture property.
     * 
     */
    public double getKolicinaStavkeFakture() {
        return kolicinaStavkeFakture;
    }

    /**
     * Sets the value of the kolicinaStavkeFakture property.
     * 
     */
    public void setKolicinaStavkeFakture(double value) {
        this.kolicinaStavkeFakture = value;
    }

    /**
     * Gets the value of the ukupanIznos property.
     * 
     */
    public double getUkupanIznos() {
        return ukupanIznos;
    }

    /**
     * Sets the value of the ukupanIznos property.
     * 
     */
    public void setUkupanIznos(double value) {
        this.ukupanIznos = value;
    }

    /**
     * Gets the value of the proizvod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProizvod() {
        return proizvod;
    }

    /**
     * Sets the value of the proizvod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProizvod(String value) {
        this.proizvod = value;
    }

}
