
package com.project.clientWs;

import com.project.ws.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankServicePort", targetNamespace = "http://poslovna.com/soap-example")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankServicePort {


    /**
     * 
     * @param exportNalogaRequest
     * @return
     *     returns com.poslovna.soap_example.ExportNalogaResponse
     */
    @WebMethod
    @WebResult(name = "exportNalogaResponse", targetNamespace = "http://poslovna.com/soap-example", partName = "exportNalogaResponse")
    public ExportNalogaResponse exportNaloga(
        @WebParam(name = "exportNalogaRequest", targetNamespace = "http://poslovna.com/soap-example", partName = "exportNalogaRequest")
                ExportNalogaRequest exportNalogaRequest);

    /**
     * 
     * @param importFakturaRequest
     * @return
     *     returns com.poslovna.soap_example.ImportFakturaResponse
     */
    @WebMethod
    @WebResult(name = "importFakturaResponse", targetNamespace = "http://poslovna.com/soap-example", partName = "importFakturaResponse")
    public ImportFakturaResponse importFaktura(
        @WebParam(name = "importFakturaRequest", targetNamespace = "http://poslovna.com/soap-example", partName = "importFakturaRequest")
                ImportFakturaRequest importFakturaRequest);

    /**
     * 
     * @param importIzvodRequest
     * @return
     *     returns com.poslovna.soap_example.ImportIzvodResponse
     */
    @WebMethod
    @WebResult(name = "importIzvodResponse", targetNamespace = "http://poslovna.com/soap-example", partName = "importIzvodResponse")
    public ImportIzvodResponse importIzvod(
        @WebParam(name = "importIzvodRequest", targetNamespace = "http://poslovna.com/soap-example", partName = "importIzvodRequest")
        ImportIzvodRequest importIzvodRequest);

}
